task_homepage:
    path:     /list
    defaults: { _controller: TaskBundle:Item:index }
    
task_view:
    path:      /task/view/{id}
    defaults: { _controller: TaskBundle:Item:view }
    requirements:
        id: \d+
    
task_add:
    path:      /task/add
    defaults: { _controller: TaskBundle:Item:add }

task_edit:
    path:     /task/edit/{id}
    defaults: { _controller: TaskBundle:Item:edit }
    requirements:
        id: \d+
task_delete:
    path:     /task/delete/{id}
    defaults: { _controller: TaskBundle:Item:delete }
    requirements:
        id: \d+