# app/config/security.yml

security:
  encoders:
    UserBundle\Entity\User:
        algorithm: bcrypt

  role_hierarchy:
    ROLE_ADMIN:       ROLE_USER
    ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

  providers:
        our_db_provider:
            entity:
                class: UserBundle:User
                property: username
                # if you're using multiple entity managers
                # manager_name: customer

  firewalls:
      main:
          pattern:    ^/(task|user)
          http_basic: ~
          provider: our_db_provider
      homepage:
          pattern:   ^/
          anonymous: ~
