# app/config/security.yml

security:
  encoders:
    UserBundle\Entity\User:
        algorithm: bcrypt

  role_hierarchy:
    ROLE_ADMIN:       ROLE_USER
    ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

  providers:
        our_db_provider:
            entity:
                class: UserBundle:User
                property: username
                # if you're using multiple entity managers
                # manager_name: customer

  firewalls:
      main_login:
        # Cette expression régulière permet de prendre /login (mais pas /login_check !)
          pattern:    ^/login$
          anonymous: true # On autorise alors les anonymes sur ce pare-feu
      main:
          pattern:    ^/
          anonymous: ~
          provider: our_db_provider
          anonymous: ~
          form_login:
              login_path: login
              check_path: login_check
          logout:
              path:       logout
              target:     login
     # homepage:
     #     pattern:   ^/
     #     anonymous: ~
